
name: test-github-workflow

on:
  push:
    branches:
      - test-github-workflow
      
jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: python markdownparser.py
